# Generated by Django 4.2.6 on 2023-10-14 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_formsubmited_maiden_name_documentlc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentlc',
            name='diso',
        ),
        migrations.AddField(
            model_name='documentlc',
            name='local_council',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='documentlc',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='DocumentDISO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('diso', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.formsubmited')),
            ],
        ),
    ]
