# Generated by Django 4.2.6 on 2023-10-14 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_remove_documentlc_diso_documentlc_local_council_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('local_council', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('diso', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.formsubmited')),
            ],
        ),
        migrations.RemoveField(
            model_name='documentlc',
            name='applicant',
        ),
        migrations.DeleteModel(
            name='DocumentDISO',
        ),
        migrations.DeleteModel(
            name='DocumentLC',
        ),
    ]
