# Generated by Django 4.2.6 on 2023-10-14 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_documents_remove_documentlc_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.formsubmited'),
        ),
    ]
